Name:           ros-hydro-hector-pose-estimation
Version:        0.2.0
Release:        1%{?dist}
Summary:        ROS hector_pose_estimation package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/hector_pose_estimation
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-hector-pose-estimation-core
Requires:       ros-hydro-message-filters
Requires:       ros-hydro-nav-msgs
Requires:       ros-hydro-nodelet
Requires:       ros-hydro-sensor-msgs
Requires:       ros-hydro-tf
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-hector-pose-estimation-core
BuildRequires:  ros-hydro-message-filters
BuildRequires:  ros-hydro-nav-msgs
BuildRequires:  ros-hydro-nodelet
BuildRequires:  ros-hydro-sensor-msgs
BuildRequires:  ros-hydro-tf

%description
hector_pose_estimation provides the hector_pose_estimation node and the
hector_pose_estimation nodelet.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Tue Feb 24 2015 Johannes Meyer <meyer@fsr.tu-darmstadt.de> - 0.2.0-1
- Autogenerated by Bloom

* Sun Feb 22 2015 Johannes Meyer <meyer@fsr.tu-darmstadt.de> - 0.2.0-0
- Autogenerated by Bloom

* Thu Oct 02 2014 Johannes Meyer <meyer@fsr.tu-darmstadt.de> - 0.1.5-0
- Autogenerated by Bloom

